# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "cp-cp"
repo_name: "my-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/my-arxiv-daily.json'
json_gitpage_path: './docs/my-arxiv-daily-web.json'
json_wechat_path: './docs/my-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Image Generation":
        filters: ["Image Generation"]
    "Video Generation":
        filters: ["Video Generation"]
    "Image Editing":
        filters: ["Image Editing"]
